# Generated by Django 3.1.5 on 2021-01-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_family', models.BooleanField(db_column='BIG_FAMILY')),
                ('comment', models.CharField(db_column='COMMENT', max_length=256)),
                ('date_of_birth', models.DateField(db_column='BIRTH_DAY')),
                ('email', models.EmailField(db_column='EMAIL', max_length=64)),
                ('father_name', models.CharField(db_column='FATHER_NAME', max_length=25)),
                ('father_surname', models.CharField(db_column='FATHER_SURNAME', max_length=35)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=25)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=35)),
                ('id_number', models.CharField(db_column='ID_NUMBER', max_length=10)),
                ('id_number_authority', models.CharField(db_column='ID_NUMBER_AUTHORITY', max_length=64)),
                ('is_man', models.BooleanField(db_column='MAN')),
                ('mother_name', models.CharField(db_column='MOTHER_NAME', max_length=25)),
                ('mother_surname', models.CharField(db_column='MOTHER_SURNAME', max_length=35)),
                ('vat_number', models.CharField(db_column='VAT_NUMBER', max_length=10)),
                ('type', models.CharField(choices=[('DEPUTY', 'Αναπληρωτής'), ('REGULAR', 'Μόνιμος'), ('HOURLYPAID', 'Ωρομίσθιος'), ('ADMINISTRATIVE', 'Διοικητικός')], db_column='EMPLOYEE_TYPE', default='REGULAR', max_length=32)),
                ('maritalType', models.CharField(choices=[('UNKNOWN', 'Άγνωστο'), ('SINGLE', 'Άγαμος'), ('MARRIED', 'Έγγαμος'), ('DIVORCED', 'Διαζευγμένος'), ('WIDOWER', 'Χηρεία')], db_column='MARITAL_STATUS', default='UNKNOWN', max_length=30)),
            ],
        ),
    ]
