# Generated by Django 3.1.5 on 2021-10-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20211013_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(db_column='FATHER_NAME', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_surname',
            field=models.CharField(db_column='FATHER_SURNAME', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(db_column='ID_NUMBER', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number_authority',
            field=models.CharField(db_column='ID_NUMBER_AUTHORITY', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(db_column='MOTHER_NAME', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother_surname',
            field=models.CharField(db_column='MOTHER_SURNAME', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vat_number',
            field=models.CharField(db_column='VAT_NUMBER', max_length=10, null=True),
        ),
    ]
