# Generated by Django 3.1.5 on 2021-10-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20211014_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='CODE', max_length=9, unique=True)),
                ('title', models.CharField(db_column='TITLE', max_length=70)),
                ('public_code', models.CharField(db_column='PUBLIC_CODE', max_length=9, null=True)),
                ('public_title', models.CharField(db_column='PUBLIC_TITLE', max_length=70, null=True)),
                ('disabled', models.BooleanField(db_column='DISABLED', default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='specialization',
            index=models.Index(fields=['title', 'public_title'], name='employees_s_TITLE_06554a_idx'),
        ),
        migrations.AddIndex(
            model_name='specialization',
            index=models.Index(fields=['disabled'], name='employees_s_DISABLE_0e9f80_idx'),
        ),
    ]
