# Generated by Django 4.0.2 on 2022-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_id_alter_specialization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='registry_id',
            field=models.CharField(db_column='REGISTRY_ID', default=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vat_number',
            field=models.CharField(db_column='VAT_NUMBER', default=True, max_length=10, null=True),
        ),
    ]
