# Generated by Django 4.0.2 on 2022-03-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_school_public_sector_generalunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='points',
            field=models.PositiveSmallIntegerField(db_column='POINTS', default=0),
        ),
    ]
