# Generated by Django 4.0.2 on 2022-03-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_school_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalunit',
            name='minoas_id',
            field=models.IntegerField(db_column='MINOAS_ID', default=None, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='minoas_id',
            field=models.IntegerField(db_column='MINOAS_ID', default=None, unique=True),
        ),
    ]
