# Generated by Django 4.0.2 on 2022-03-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_school_ministry_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='ministry_code',
            field=models.CharField(db_column='MINISTRY_CODE', max_length=7, null=True),
        ),
    ]
