# Generated by Django 4.0.2 on 2022-03-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_unit_remove_school_address_delete_generalunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.unit'),
        ),
    ]
