# Generated by Django 4.0.10 on 2023-04-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=False)),
                ('title', models.CharField(db_column='TITLE', max_length=64)),
                ('date_from', models.DateField(db_column='DATE_FROM')),
                ('date_until', models.DateField(db_column='DATE_UNTIL')),
            ],
        ),
        migrations.AddIndex(
            model_name='schoolyear',
            index=models.Index(fields=['is_active'], name='main_school_IS_ACTI_7467a9_idx'),
        ),
    ]
