# Generated by Django 4.0.10 on 2023-05-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schoolyear',
            name='main_school_IS_ACTI_7467a9_idx',
        ),
        migrations.RemoveField(
            model_name='schoolyear',
            name='title',
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='year',
            field=models.PositiveIntegerField(db_column='YEAR', default=0),
            preserve_default=False,
        ),
    ]
