# Generated by Django 3.1.5 on 2021-10-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_auto_20211019_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(db_column='IS_ACTIVE', db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='legacy_code',
            field=models.CharField(db_column='LEGACY_CODE', db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='suitable_for_employee_type',
            field=models.CharField(choices=[('DEPUTY', 'Αναπληρωτής'), ('REGULAR', 'Μόνιμος'), ('HOURLYPAID', 'Ωρομίσθιος'), ('ADMINISTRATIVE', 'Διοικητικός')], db_column='EMPLOYEE_TYPE', db_index=True, default='REGULAR', max_length=32),
        ),
    ]
