# Generated by Django 3.1.5 on 2021-10-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_auto_20211019_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='deleted_comment',
            field=models.TextField(db_column='DELETED_COMMENT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='deleted_on',
            field=models.DateField(db_column='DELETED_ON', null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_deleted',
            field=models.BooleanField(db_column='IS_DELETED', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='comment',
            field=models.TextField(db_column='COMMENT', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='is_active',
            field=models.BooleanField(db_column='IS_ACTIVE', db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'leave_type'], name='leaves_leav_EMPLOYE_da2b90_idx'),
        ),
    ]
