# Generated by Django 3.1.13 on 2021-11-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_auto_20211020_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='minoas_id',
            field=models.IntegerField(db_column='MINOAS_ID', default=None, null=True, unique=True),
        ),
    ]
