# Generated by Django 3.1.13 on 2022-02-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_auto_20220128_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='comment',
            field=models.TextField(blank=True, db_column='COMMENT', help_text='Εισάγεται τυχόν σχόλια που έχετε για την άδεια', max_length=255, null=True, verbose_name='Σχόλια Άδειας'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='deleted_comment',
            field=models.TextField(db_column='DELETED_COMMENT', help_text='Προαιρετικά εισάγεται σχόλιο ή περιγραφή διαγραφής της άδειας', max_length=255, null=True, verbose_name='Σχόλιο Διαγραφής'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='effective_number_of_days',
            field=models.IntegerField(db_column='EFFECTIVE_DAYS_COUNT', help_text='Καταχωρίστε την πραγματική διάρκειας της άδειας', null=True, verbose_name='Διάρκεια Άδειας'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='number_of_days',
            field=models.IntegerField(db_column='DAYS_COUNT', help_text='Ημερολογιακή Διάρκεια Άδειας. Υπολογίζεται αυτόματα απο την Ημ/νια Έναρξης και Λήξεις της άδειας', null=True, verbose_name='Ημερολογιακή Διάρκεια Άδειας'),
        ),
    ]
