# Generated by Django 3.1.13 on 2022-02-16 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0010_auto_20220211_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='created_on',
            field=models.DateTimeField(db_column='CREATED_ON', default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='leave',
            name='updated_on',
            field=models.DateTimeField(blank=True, db_column='UPDATED_ON', null=True),
        ),
    ]
