# Generated by Django 3.1.13 on 2022-02-16 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_auto_20220216_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='created_on',
            field=models.DateTimeField(db_column='CREATED_ON', default=datetime.datetime.utcnow),
        ),
    ]
