# Generated by Django 4.0.2 on 2022-03-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0013_alter_leave_id_alter_leavetype_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['minoas_id'], name='leaves_leav_MINOAS__223ffa_idx'),
        ),
    ]
