# Generated by Django 4.0.7 on 2023-02-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0015_alter_leave_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='health_committee_protocol',
            field=models.TextField(blank=True, db_column='HEALTH_COMMITTEE_PROTOCOL', default='', help_text='Καταχωρίστε το Πρωτόκολλο Υγειονομικής Επιτροπής', max_length=128, verbose_name='Πρωτόκολλο Υγειονομικής Επιτροπής'),
        ),
        migrations.AddField(
            model_name='leave',
            name='incoming_protocol',
            field=models.TextField(blank=True, db_column='INCOMING_PROTOCOL', default='', help_text='Καταχωρίστε τον αριθμό του εισερχόμενου πρωτοκόλλου', max_length=64, verbose_name='Αριθμός Εισερχόμενου Πρωτοκόλλου'),
        ),
        migrations.AddField(
            model_name='leave',
            name='incoming_protocol_date',
            field=models.DateField(db_column='INCOMING_PROTOCOL_DATE', default=None, help_text='Καταχωρίστε την ημ/νία του εισερχόμενου πρωτοκόλλου', null=True, verbose_name='Ημ/νια Εισερχόμενου Πρωτοκόλλου'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='comment',
            field=models.TextField(blank=True, db_column='COMMENT', help_text='Εισάγετε τυχόν σχόλια που έχετε για την άδεια', max_length=255, null=True, verbose_name='Σχόλια Άδειας'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='deleted_comment',
            field=models.TextField(db_column='DELETED_COMMENT', help_text='Προαιρετικά εισάγετε σχόλιο ή περιγραφή διαγραφής της άδειας', max_length=255, null=True, verbose_name='Σχόλιο Διαγραφής'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='number_of_days',
            field=models.IntegerField(db_column='DAYS_COUNT', help_text='Ημερολογιακή Διάρκεια Άδειας. Υπολογίζεται αυτόματα απο την Ημ/νια Έναρξης και Λήξης της άδειας', null=True, verbose_name='Ημερολογιακή Διάρκεια Άδειας'),
        ),
    ]
