# Generated by Django 4.0.7 on 2023-02-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0017_alter_leave_health_committee_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='health_committee_protocol',
            field=models.CharField(blank=True, db_column='HEALTH_COMMITTEE_PROTOCOL', default='', help_text='Καταχωρίστε το πρωτόκολλο της γνωμάτευσης της Α/θμιας Υγειονομικής Επιτροπής', max_length=128, verbose_name='Πρωτόκολλο Γνωμάτευσης Υγ. Επιτροπής'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='incoming_protocol_date',
            field=models.DateField(blank=True, db_column='INCOMING_PROTOCOL_DATE', default=None, help_text='Καταχωρίστε την ημ/νία του εισερχόμενου πρωτοκόλλου', null=True, verbose_name='Ημ/νια Εισερχόμενου Πρωτοκόλλου'),
        ),
    ]
