# Generated by Django 4.0.10 on 2023-05-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0020_alter_leavetype_minoas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='suitable_for_employee_type',
            field=models.CharField(choices=[('DEPUTY', 'Αναπληρωτής'), ('REGULAR', 'Μόνιμος'), ('HOURLYPAID', 'Ωρομίσθιος'), ('IDAX', 'Ιδιωτικού Δικαίου Αορίστου Χρόνου (Ι.Δ.Α.Χ.)'), ('ADMINISTRATIVE', 'Διοικητικός')], db_column='EMPLOYEE_TYPE', db_index=True, default='REGULAR', max_length=32),
        ),
    ]
