# Generated by Django 4.0.10 on 2023-11-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0021_alter_leavetype_suitable_for_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='health_committee_protocol',
            field=models.CharField(blank=True, db_column='HEALTH_COMMITTEE_PROTOCOL', default='', help_text='Καταχωρίστε το πρωτόκολλο της γνωμάτευσης της Α/θμιας Υγειονομικής Επιτροπής', max_length=128, verbose_name='Πρωτόκολλο Υγειονομικής Επιτροπής ή Πρωτόκολλο Βεβαίωσης Δ/ντη Σχολ. Μονάδας ή Ημερομηνία Γνωμάτευσης Ιατρού ή Ημερομηνία Υπεύθυνης Δήλωσης'),
        ),
    ]
