# Generated by Django 4.0.10 on 2023-12-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0022_alter_leave_health_committee_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='count_against_teaching_experience',
            field=models.BooleanField(blank=True, db_column='NO_TEACHING_EXPERIENCE', default=None, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='count_against_teaching_experience',
            field=models.BooleanField(db_column='NO_TEACHING_EXPERIENCE', default=False),
        ),
    ]
