# Generated by Django 4.0.10 on 2024-01-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0023_leave_count_against_teaching_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='count_against_teaching_experience',
            field=models.BooleanField(blank=True, db_column='NO_TEACHING_EXPERIENCE', default=None, help_text='Επιλέξτε αν η άδεια αφαιρεί μέρες απο την Εκπαιδευτική Υπηρεσία', null=True, verbose_name='Αφαιρεί Εκπαιδευτική Υπηρεσία'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='deleted_comment',
            field=models.TextField(blank=True, db_column='DELETED_COMMENT', help_text='Προαιρετικά εισάγετε σχόλιο ή περιγραφή διαγραφής της άδειας', max_length=255, null=True, verbose_name='Σχόλιο Διαγραφής'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='deleted_on',
            field=models.DateField(blank=True, db_column='DELETED_ON', null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='minoas_id',
            field=models.IntegerField(blank=True, db_column='MINOAS_ID', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='count_against_teaching_experience',
            field=models.BooleanField(db_column='NO_TEACHING_EXPERIENCE', default=False, help_text='Επιλέξτε αν η άδεια αφαιρεί μέρες απο την Εκπαιδευτική Υπηρεσία', verbose_name='Αφαιρεί Εκπαιδευτική Υπηρεσία'),
        ),
    ]
