# Generated by Django 4.0.10 on 2024-01-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0024_alter_leave_count_against_teaching_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='issued_on',
            field=models.DateTimeField(blank=True, db_column='ISSUED_ON', default=None, help_text='Καταχωρίστε την ημ/νια έκδοσης της απόφασης της άδειας', null=True, verbose_name='Ημ/νια έκδοσης της απόφασης'),
        ),
    ]
