# Generated by Django 4.0.10 on 2024-01-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0026_alter_leave_issued_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='original_leave',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaves.leave'),
        ),
    ]
