# Generated by Django 3.1.5 on 2021-10-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='basic_type',
            field=models.CharField(choices=[('UNPAID_LEAVE', 'Άνευ Αποδοχών'), ('REGULAR_LEAVE', 'Κανονική Άδεια'), ('GENERIC_LEAVE', 'Γενική Άδεια')], db_column='BASIC_TYPE', default='REGULAR_LEAVE', max_length=32),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='description',
            field=models.CharField(db_column='DESCRIPTION', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='legacy_code',
            field=models.CharField(db_column='LEGACY_CODE', max_length=32, unique=True),
        ),
    ]
