# Generated by Django 3.1.5 on 2021-10-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_auto_20211019_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='minoas_id',
            field=models.IntegerField(db_column='MINOAS_ID', default=None, unique=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='minoas_id',
            field=models.IntegerField(db_column='MINOAS_ID', default=None, unique=True),
        ),
    ]
