# Generated by Django 3.1.5 on 2021-10-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20211013_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='minoas_id',
            field=models.IntegerField(db_column='MINOAS_ID', default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employees_e_LAST_NA_62c525_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['vat_number'], name='employees_e_VAT_NUM_d200e6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['type'], name='employees_e_EMPLOYE_83fce3_idx'),
        ),
    ]
