# Generated by Django 3.1.5 on 2021-10-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20211015_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.specialization'),
        ),
    ]
