# Generated by Django 4.0.2 on 2022-03-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_registry_id_alter_employee_vat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(db_column='ADDRESS_LINE_1', max_length=128)),
                ('postal_code', models.CharField(db_column='POSTAL_CODE', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='TITLE', max_length=80, unique=True)),
                ('ministry_code', models.CharField(db_column='MINISTRY_CODE', max_length=7, unique=True)),
                ('school_type', models.CharField(choices=[('EPAL_SCHOOL_TYPE', 'ΕΠΑΛ'), ('EPAS_SCHOOL_TYPE', 'ΕΠΑΣ'), ('GEL_SCHOOL_TYPE', 'ΓΕΛ'), ('GYM_SCHOOL_TYPE', 'ΓΥΜ'), ('SMEAE_SCHOOL_TYPE', 'ΣΜΕΑΕ')], db_column='SCHOOL_TYPE', default='GEL_SCHOOL_TYPE', max_length=28)),
                ('address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
