# Generated by Django 4.0.2 on 2022-03-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_address_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='public_sector',
            field=models.BooleanField(db_column='PUBLIC_SECTOR', default=True),
        ),
        migrations.CreateModel(
            name='GeneralUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='TITLE', max_length=80, unique=True)),
                ('public_sector', models.BooleanField(db_column='PUBLIC_SECTOR', default=True)),
                ('address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
