# Generated by Django 4.0.2 on 2022-03-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_generalunit_minoas_id_school_minoas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='ministry_code',
            field=models.CharField(db_column='MINISTRY_CODE', max_length=7),
        ),
    ]
