# Generated by Django 4.0.2 on 2022-03-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_school_ministry_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minoas_id', models.IntegerField(db_column='MINOAS_ID', unique=True)),
                ('title', models.CharField(db_column='TITLE', max_length=80, unique=True)),
                ('public_sector', models.BooleanField(db_column='PUBLIC_SECTOR', default=True)),
                ('ministry_code', models.CharField(db_column='MINISTRY_CODE', max_length=7, null=True)),
                ('unit_type', models.CharField(choices=[('SCHOOL', 'ΣΧΟΛΕΙΟ'), ('OTHER', 'ΑΛΛΟ')], db_column='UNIT_TYPE', default='SCHOOL', max_length=28)),
                ('school_type', models.CharField(choices=[('EPAL', 'ΕΠΑΛ'), ('EPAS', 'ΕΠΑΣ'), ('GEL', 'ΓΕΛ'), ('GYM', 'ΓΥΜ'), ('SMEAE', 'ΣΜΕΑΕ'), ('OTHER', 'ΑΛΛΟ')], db_column='SCHOOL_TYPE', default=None, max_length=28, null=True)),
                ('points', models.PositiveSmallIntegerField(db_column='POINTS', default=0)),
                ('address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.address')),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.DeleteModel(
            name='GeneralUnit',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['title'], name='employees_u_TITLE_9c6a10_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_type', 'school_type'], name='employees_u_UNIT_TY_a10c6e_idx'),
        ),
    ]
