# Generated by Django 4.0.2 on 2022-06-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_employee_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_VAT_NUM_d200e6_idx',
        ),
        migrations.AddField(
            model_name='employee',
            name='address_city',
            field=models.CharField(db_column='ADDRESS_CITY', default=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_line',
            field=models.CharField(db_column='ADDRESS_LINE', default=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_zip',
            field=models.CharField(db_column='ADDRESS_ZIP', default=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='amka',
            field=models.CharField(db_column='AMKA', default=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.CharField(db_column='TELEPHONE', default=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_id',
            field=models.CharField(db_column='REGISTRY_ID', db_index=True, default=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vat_number',
            field=models.CharField(db_column='VAT_NUMBER', db_index=True, default=True, max_length=10, null=True),
        ),
    ]
