# Generated by Django 4.0.2 on 2022-06-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_remove_employee_employees_e_vat_num_d200e6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(db_index=True)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
    ]
