# Generated by Django 4.0.2 on 2022-06-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_employeetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type_extended',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeetype'),
        ),
        migrations.AddField(
            model_name='employeetype',
            name='legacy_type',
            field=models.CharField(choices=[('DEPUTY', 'Αναπληρωτής'), ('REGULAR', 'Μόνιμος'), ('HOURLYPAID', 'Ωρομίσθιος'), ('ADMINISTRATIVE', 'Διοικητικός')], default='REGULAR', max_length=32),
        ),
    ]
