# Generated by Django 4.0.2 on 2022-06-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_employee_employee_type_extended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='imported_from_athina',
            field=models.DateTimeField(db_column='ATHINA_IMPORTED', default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_from_athina',
            field=models.DateTimeField(db_column='ATHINA_UPDATED', default=None, null=True),
        ),
    ]
