# Generated by Django 4.0.2 on 2022-06-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_employee_imported_from_athina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address_city',
            field=models.CharField(db_column='ADDRESS_CITY', default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_line',
            field=models.CharField(db_column='ADDRESS_LINE', default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_zip',
            field=models.CharField(db_column='ADDRESS_ZIP', default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.CharField(db_column='TELEPHONE', default=None, max_length=32, null=True),
        ),
    ]
