# Generated by Django 4.0.2 on 2022-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_alter_employee_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='minoas_id',
            field=models.IntegerField(db_column='MINOAS_ID', db_index=True, default=None, null=True),
        ),
    ]
