# Generated by Django 4.0.2 on 2022-06-20 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_alter_employee_minoas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(db_column='CREATED_ON', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_comment',
            field=models.TextField(db_column='DELETED_COMMENT', default=None, help_text='Προαιρετικά εισάγεται σχόλιο ή περιγραφή διαγραφής', max_length=255, null=True, verbose_name='Σχόλιο Διαγραφής'),
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_on',
            field=models.DateField(db_column='DELETED_ON', default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_on',
            field=models.DateTimeField(blank=True, db_column='UPDATED_ON', null=True),
        ),
    ]
