# Generated by Django 4.0.2 on 2022-06-27 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_employee_created_on_employee_deleted_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperienceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(db_column='DATE_FROM', help_text='Καταχωρίστε την ημ/νια έναρξης', verbose_name='Έναρξη Υπηρεσίας')),
                ('date_until', models.DateField(db_column='DATE_UNTIL', help_text='Καταχωρίστε την ημ/νια λήξης', verbose_name='Λήξη Υπηρεσίας')),
                ('comment', models.TextField(blank=True, db_column='COMMENT', help_text='Εισάγεται τυχόν σχόλια που έχετε για την υπηρεσία', max_length=255, null=True, verbose_name='Σχόλια Υπηρεσίας')),
                ('created_on', models.DateTimeField(db_column='CREATED_ON', default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(blank=True, db_column='UPDATED_ON', null=True)),
                ('work_duration_total_in_days', models.IntegerField(db_column='DURATION_TOTAL_DAYS', default=0)),
                ('work_duration_days', models.PositiveSmallIntegerField(db_column='DURATION_DAYS', default=0)),
                ('work_duration_months', models.PositiveSmallIntegerField(db_column='DURATION_MONTHS', default=0)),
                ('work_duration_years', models.PositiveSmallIntegerField(db_column='DURATION_YEARS', default=0)),
                ('document_number', models.CharField(db_column='DOCUMENT_NUMBER', default=None, max_length=32, null=True)),
                ('document_date', models.DateField(db_column='DOCUMENT_DATE', null=True)),
                ('authority', models.CharField(db_column='AUTHORITY', max_length=128, null=True)),
                ('leave_type', models.ForeignKey(db_column='WORK_EXPERIENCE_TYPE_ID', help_text='Επιλέξτε τον τύπος της Υπηρεσίας', on_delete=django.db.models.deletion.PROTECT, to='employees.workexperiencetype', verbose_name='Τύπος Υπηρεσίας')),
            ],
        ),
    ]
