# Generated by Django 4.0.2 on 2022-06-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_workexperiencetype_workexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='leave_type',
            new_name='work_experience_type',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
            preserve_default=False,
        ),
    ]
