# Generated by Django 4.0.2 on 2022-06-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_rename_leave_type_workexperience_work_experience_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='work_duration_days',
            new_name='duration_days',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='work_duration_months',
            new_name='duration_months',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='work_duration_total_in_days',
            new_name='duration_total_in_days',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='work_duration_years',
            new_name='duration_years',
        ),
    ]
