# Generated by Django 4.0.2 on 2022-06-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_rename_work_duration_days_workexperience_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='date_from',
            field=models.DateField(db_column='DATE_FROM', default=None, help_text='Καταχωρίστε την ημ/νια έναρξης', null=True, verbose_name='Έναρξη Υπηρεσίας'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='date_until',
            field=models.DateField(db_column='DATE_UNTIL', default=None, help_text='Καταχωρίστε την ημ/νια λήξης', null=True, verbose_name='Λήξη Υπηρεσίας'),
        ),
    ]
