# Generated by Django 4.0.2 on 2022-09-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_alter_workexperience_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fek_diorismou',
            field=models.CharField(db_column='FEK_DORISMOU', default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fek_diorismou_date',
            field=models.DateField(db_column='FEK_DIORISMOU_DATE', default=None, null=True),
        ),
    ]
