# Generated by Django 4.0.2 on 2022-09-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_alter_employee_fek_diorismou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(db_column='ID_NUMBER', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_id',
            field=models.CharField(db_column='REGISTRY_ID', db_index=True, default=True, max_length=32, null=True),
        ),
    ]
