# Generated by Django 4.0.2 on 2022-10-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_alter_employee_id_number_alter_employee_registry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bathmos',
            field=models.CharField(db_column='BATHMOS', default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_workday_date',
            field=models.DateField(db_column='FIRST_WORKDAY_DATE', default=None, help_text='Ημερομηνία 1ης Ανάληψης Υπηρεσίας', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='imported_from_myschool',
            field=models.DateTimeField(db_column='MYSCHOOL_IMPORTED', default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mandatory_week_workhours',
            field=models.PositiveSmallIntegerField(db_column='WORK_HOURS', default=None, help_text='Υποχρεωτικό Διδακτικό Ωράριο', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mk',
            field=models.CharField(db_column='MK', default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_from_myschool',
            field=models.DateTimeField(db_column='MYSCHOOL_UPDATED', default=None, null=True),
        ),
    ]
