# Generated by Django 4.0.2 on 2022-10-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0037_employee_bathmos_employee_first_workday_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='myschool_title',
            field=models.CharField(blank=True, db_column='MYSCHOOL_TITLE', default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ministry_code',
            field=models.CharField(db_column='MINISTRY_CODE', db_index=True, max_length=7, null=True),
        ),
    ]
