# Generated by Django 4.0.2 on 2022-10-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0039_alter_unit_address_alter_unit_minoas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
