# Generated by Django 4.0.2 on 2022-10-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0041_employee_email_employee_email_psd'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, db_column='MOBILE', default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, db_column='TELEPHONE', default=None, max_length=32, null=True),
        ),
    ]
