# Generated by Django 4.0.2 on 2022-12-14 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0043_alter_employee_amka_alter_employee_registry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CREATED_ON', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deleted_comment',
            field=models.TextField(blank=True, db_column='DELETED_COMMENT', default=None, help_text='Προαιρετικά εισάγεται σχόλιο ή περιγραφή διαγραφής', max_length=255, null=True, verbose_name='Σχόλιο Διαγραφής'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deleted_on',
            field=models.DateField(blank=True, db_column='DELETED_ON', default=None, null=True),
        ),
    ]
