# Generated by Django 4.0.2 on 2022-12-14 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0045_alter_employee_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='amka',
            field=models.CharField(blank=True, db_column='AMKA', default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='big_family',
            field=models.BooleanField(blank=True, db_column='BIG_FAMILY', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='comment',
            field=models.CharField(blank=True, db_column='COMMENT', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, db_column='BIRTH_DAY', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type_extended',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeetype'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_surname',
            field=models.CharField(blank=True, db_column='FATHER_SURNAME', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(blank=True, db_column='ID_NUMBER', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number_authority',
            field=models.CharField(blank=True, db_column='ID_NUMBER_AUTHORITY', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_man',
            field=models.BooleanField(blank=True, db_column='MAN', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='minoas_id',
            field=models.IntegerField(blank=True, db_column='MINOAS_ID', db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, db_column='MOTHER_NAME', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother_surname',
            field=models.CharField(blank=True, db_column='MOTHER_SURNAME', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_id',
            field=models.CharField(blank=True, db_column='REGISTRY_ID', db_index=True, default=None, max_length=32, null=True),
        ),
    ]
