# Generated by Django 4.0.7 on 2022-12-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0049_auto_20221216_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='public_id',
            new_name='uuid',
        ),
    ]
