# Generated by Django 4.0.7 on 2023-02-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0050_rename_public_id_employee_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='deleted_comment',
            field=models.TextField(blank=True, db_column='DELETED_COMMENT', default=None, help_text='Προαιρετικά εισάγετε σχόλιο ή περιγραφή διαγραφής', max_length=255, null=True, verbose_name='Σχόλιο Διαγραφής'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='comment',
            field=models.TextField(blank=True, db_column='COMMENT', help_text='Εισάγετε τυχόν σχόλια που έχετε για την υπηρεσία', max_length=255, null=True, verbose_name='Σχόλια Υπηρεσίας'),
        ),
    ]
