# Generated by Django 4.0.10 on 2023-03-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0051_alter_employee_deleted_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetype',
            name='code',
        ),
        migrations.AddField(
            model_name='employeetype',
            name='athina_code',
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='legacy_type',
            field=models.CharField(choices=[('DEPUTY', 'Αναπληρωτής'), ('REGULAR', 'Μόνιμος'), ('HOURLYPAID', 'Ωρομίσθιος'), ('ADMINISTRATIVE', 'Διοικητικός')], db_index=True, default='REGULAR', max_length=32),
        ),
    ]
