# Generated by Django 4.0.10 on 2023-03-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0053_alter_employeetype_athina_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type_extended',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeetype'),
        ),
    ]
