# Generated by Django 4.0.10 on 2023-03-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0052_alter_specialization_code_and_more'),
        ('employees', '0054_alter_employee_employee_type_extended'),
    ]

    operations = [
    ]
