# Generated by Django 4.0.10 on 2023-04-07 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('employees', '0055_merge_20230330_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('legacy_type', models.CharField(choices=[('DEPUTY', 'Αναπληρωτής'), ('REGULAR', 'Μόνιμος'), ('HOURLYPAID', 'Ωρομίσθιος'), ('ADMINISTRATIVE', 'Διοικητικός')], db_index=True, default='REGULAR', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('employment_type', models.CharField(choices=[('DEPUTY', 'Αναπληρωτής'), ('REGULAR', 'Μόνιμος'), ('HOURLYPAID', 'Ωρομίσθιος'), ('ADMINISTRATIVE', 'Διοικητικός')], db_column='EMPLOYMENT_TYPE', default='REGULAR', max_length=32)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', db_index=True, default=True)),
                ('mandatory_week_workhours', models.PositiveSmallIntegerField(blank=True, db_column='WORK_HOURS', default=None, help_text='Υποχρεωτικό Διδακτικό Ωράριο', null=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_until', models.DateField()),
                ('praksi_topothetisis', models.CharField(blank=True, db_column='PRAKSI_TOPOTHETISIS', default=None, max_length=64, null=True)),
                ('praksi_topothetisis_date', models.DateField(blank=True, db_column='PRAKSI_TOPOTHETISIS_DATE', default=None, null=True)),
                ('deleted_on', models.DateField(blank=True, db_column='DELETED_ON', default=None, null=True)),
                ('deleted_comment', models.TextField(blank=True, db_column='DELETED_COMMENT', default=None, help_text='Προαιρετικά εισάγετε σχόλιο ή περιγραφή διαγραφής', max_length=255, null=True, verbose_name='Σχόλιο Διαγραφής')),
                ('created_on', models.DateTimeField(blank=True, db_column='CREATED_ON', default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(blank=True, db_column='UPDATED_ON', null=True)),
                ('updated_from_myschool', models.DateTimeField(blank=True, db_column='MYSCHOOL_UPDATED', default=None, null=True)),
                ('imported_from_myschool', models.DateTimeField(blank=True, db_column='MYSCHOOL_IMPORTED', default=None, null=True)),
                ('current_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.unit')),
                ('employment_type_extended', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employmenttype')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolyear')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.specialization')),
            ],
        ),
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['is_active'], name='employees_e_IS_ACTI_dc126a_idx'),
        ),
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['employment_type'], name='employees_e_EMPLOYM_bf6cee_idx'),
        ),
    ]
