# Generated by Django 4.0.10 on 2023-04-07 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0056_employmenttype_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='employee',
            field=models.ForeignKey(db_column='EMPLOYEE_ID', default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
            preserve_default=False,
        ),
    ]
