# Generated by Django 4.0.10 on 2023-05-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0057_employment_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmenttype',
            name='legacy_type',
        ),
    ]
