# Generated by Django 4.0.10 on 2023-05-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0058_remove_employmenttype_legacy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='week_workdays',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
