# Generated by Django 4.0.10 on 2023-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0060_employment_myschool_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='ministry_code',
            field=models.CharField(db_column='MINISTRY_CODE', db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='myschool_title',
            field=models.CharField(blank=True, db_column='MYSCHOOL_TITLE', default=None, max_length=255, null=True),
        ),
    ]
