# Generated by Django 4.0.10 on 2023-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0061_alter_unit_ministry_code_alter_unit_myschool_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='school_type',
            field=models.CharField(choices=[('EPAL', 'ΕΠΑΛ'), ('EPAS', 'ΕΠΑΣ'), ('GEL', 'ΓΕΛ'), ('GYM', 'ΓΥΜ'), ('SMEAE', 'ΣΜΕΑΕ'), ('OTHER', 'ΑΛΛΟ')], db_column='SCHOOL_TYPE', default=None, max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(db_column='TITLE', max_length=255, unique=True),
        ),
    ]
