# Generated by Django 4.0.10 on 2023-06-14 07:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_schoolyear_main_school_is_acti_7467a9_idx_and_more'),
        ('employees', '0062_alter_unit_school_type_alter_unit_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentFinancialSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=96, unique=True)),
                ('display_title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubstituteEmploymentAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('table', models.CharField(max_length=12)),
                ('table_rank', models.PositiveIntegerField()),
                ('table_points', models.FloatField()),
                ('employee', models.ForeignKey(db_column='EMPLOYEE_ID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('financing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employmentfinancialsource')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolyear')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.specialization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
