# Generated by Django 4.0.10 on 2023-11-13 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_schoolyear_main_school_is_acti_7467a9_idx_and_more'),
        ('employees', '0062_alter_unit_school_type_alter_unit_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_school_principal',
            field=models.BooleanField(db_column='IS_PRINCIPAL', default=False, help_text='Είναι Διευθυντής'),
        ),
        migrations.CreateModel(
            name='SchoolPrincipals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(db_column='DATE_FROM', verbose_name='Έναρξη')),
                ('date_until', models.DateField(db_column='DATE_UNTIL', verbose_name='Λήξη')),
                ('created_on', models.DateTimeField(db_column='CREATED_ON', default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(blank=True, db_column='UPDATED_ON', null=True)),
                ('current_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.unit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolyear')),
            ],
        ),
        migrations.AddIndex(
            model_name='schoolprincipals',
            index=models.Index(fields=['school_year', 'current_unit'], name='employees_s_school__c6fbab_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolprincipals',
            index=models.Index(fields=['employee'], name='employees_s_employe_9ebb9c_idx'),
        ),
    ]
