# Generated by Django 4.0.10 on 2023-06-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0063_employmentfinancialsource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituteEmploymentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=96, unique=True)),
                ('display_title', models.CharField(max_length=128)),
            ],
        ),
    ]
