# Generated by Django 4.0.10 on 2023-06-16 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0064_substituteemploymentsource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substituteemploymentannouncement',
            options={'verbose_name': 'Αναγγελία Πρόσληψης', 'verbose_name_plural': 'Αναγγελίες Προσλήψεων'},
        ),
        migrations.AddField(
            model_name='substituteemploymentannouncement',
            name='employment_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.substituteemploymentsource'),
            preserve_default=False,
        ),
    ]
