# Generated by Django 4.0.10 on 2023-11-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0064_remove_schoolprincipals_date_from_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schoolprincipals',
            constraint=models.UniqueConstraint(fields=('school_year', 'employee'), name='unique employee'),
        ),
    ]
