# Generated by Django 4.0.10 on 2023-11-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0065_schoolprincipals_unique employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='school_principal_unit',
            field=models.ForeignKey(blank=True, default=None, help_text='Διευθυντής σε μονάδα', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_principal_unit', to='employees.unit'),
        ),
    ]
