# Generated by Django 4.0.10 on 2023-06-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0065_alter_substituteemploymentannouncement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Α.Δ.Τ.'),
        ),
    ]
