# Generated by Django 4.0.10 on 2023-06-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0066_employee_adt'),
    ]

    operations = [
        migrations.AddField(
            model_name='substituteemploymentannouncement',
            name='phase',
            field=models.CharField(default='A', max_length=64),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='substituteemploymentannouncement',
            index=models.Index(fields=['school_year', 'financing', 'employment_source'], name='employees_s_school__2d597e_idx'),
        ),
        migrations.AddIndex(
            model_name='substituteemploymentannouncement',
            index=models.Index(fields=['specialization'], name='employees_s_special_4cb409_idx'),
        ),
        migrations.AddIndex(
            model_name='substituteemploymentannouncement',
            index=models.Index(fields=['employee'], name='employees_s_EMPLOYE_3b9b3d_idx'),
        ),
    ]
