# Generated by Django 4.0.10 on 2023-07-05 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0068_substituteemploymentannouncement_workhour_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituteEmploymentPlacementAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(db_column='CREATED_ON', default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(db_column='EMPLOYEE_ID', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
