# Generated by Django 4.0.10 on 2023-07-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0069_substituteemploymentplacementannouncement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substituteemploymentplacementannouncement',
            options={'verbose_name': 'Τοποθέτηση Αναπληρωτή', 'verbose_name_plural': 'Τοποθετήσεις Αναπληρωτών'},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['vat_number'], name='employees_e_VAT_NUM_d200e6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['registry_id'], name='employees_e_REGISTR_97ea49_idx'),
        ),
    ]
