# Generated by Django 4.0.10 on 2023-07-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0070_alter_substituteemploymentplacementannouncement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='substitute_employment_announcement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='employees.substituteemploymentannouncement'),
        ),
    ]
