# Generated by Django 4.0.10 on 2023-07-07 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_schoolyear_main_school_is_acti_7467a9_idx_and_more'),
        ('employees', '0071_employment_substitute_employment_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='substitute_employment_announcement',
        ),
        migrations.AddField(
            model_name='substituteemploymentplacementannouncement',
            name='employment',
            field=models.ForeignKey(db_column='EMPLOYMENT_ID', default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.employment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substituteemploymentplacementannouncement',
            name='employment_announcement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='employees.substituteemploymentannouncement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substituteemploymentplacementannouncement',
            name='school_year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.schoolyear'),
            preserve_default=False,
        ),
    ]
